import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.scss";

const sora = Sora({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
  preload: true,
  variable: "--font-sora",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`font-sora bg-primary text-white 
       ${sora.variable}
      `}
      >
        <main className="flex sm:hidden">{children}</main>
        <main className="hidden sm:flex min-h-screen flex-col items-center justify-center gap-6 p-24">
          <a href="#" target="_blank">
            <img src="/logo.svg" alt="logo" />
          </a>
          <div className="flex items-center flex-col gap-2">
            <h1 className="text-2xl font-semibold">
              Please resize your screen{" "}
            </h1>
            <p className="text-textmuted">it must be less than 640px</p>
          </div>
          <div className="w-1 h-1 rounded-full bg-textmuted"></div>
          <div className="flex flex-col items-center gap-2">
            <a
              className="underline underline-offset-2 text-textmuted text-sm"
              href="https://leonelngoya.com"
              target="_blank"
            >
              Code by LN
            </a>
            <a
              className="underline underline-offset-2 text-textmuted text-sm"
              href="https://bento.me/emaniui"
              target="_blank"
            >
              Design by EmaniUI
            </a>
          </div>
        </main>
      </body>
    </html>
  );
}
